---
icinga2_reserved:
  - Acknowledgement
  - ApiBindHost
  - ApiBindPort
  - ApiEnvironment
  - ApplicationType
  - AttachDebugger
  - BuildCompilerName
  - BuildCompilerVersion
  - BuildHostName
  - Concurrency
  - Critical
  - Custom
  - Deprecated
  - Down
  - DowntimeEnd
  - DowntimeRemoved
  - DowntimeStart
  - Environment
  - FlappingEnd
  - FlappingStart
  - HostDown
  - HostUp
  - IncludeConfDir
  - Internal
  - Json
  - LocalStateDir
  - LogCritical
  - LogDebug
  - LogDir
  - LogInformation
  - LogNotice
  - LogWarning
  - Math
  - MaxConcurrentChecks
  - ModAttrPath
  - NodeName
  - OK
  - ObjectsPath
  - PidPath
  - PkgDataDir
  - PlatformArchitecture
  - PlatformKernel
  - PlatformKernelVersion
  - PlatformName
  - PlatformVersion
  - PrefixDir
  - Problem
  - Recovery
  - RunAsGroup
  - RunAsUser
  - RunDir
  - ServiceCritical
  - ServiceOK
  - ServiceUnknown
  - ServiceWarning
  - StatePath
  - SysconfDir
  - System
  - Types
  - Unknown
  - Up
  - UseVfork
  - VarsPath
  - Warning
  - ZonesDir
  - Dictionary
icinga2_feature_realname:
  idomysql: ido-mysql
  ido-mysql: idomysql
  ido-pgsql: idopgsql
  idopgsql: ido-pgsql
icinga2_object_types:
  - TimePeriod
  - HostGroup
  - ServiceGroup
  - CheckerComponent
  - FileLogger
  - NotificationComponent
  - ApiListener
  - Endpoint
  - Zone
  - Host
  - Service
  - SyslogLogger
  - GraphiteWriter
  - InfluxdbWriter
  - IdoMysqlConnection
  - IdoPgsqlConnection
  - IcingaApplication
  - ApiUser
  - CheckCommand
  - NotificationCommand