icinga2_objects:
  icinga-default:
    - name: agent.localdomain
      type: Endpoint
      file: zones.d/main/hosts/agent.localdomain.conf
    - name: agent.localdomain
      type: Zone
      file: zones.d/main/hosts/agent.localdomain.conf
      parent: main
      endpoints:
        - agent.localdomain
    - name: agent.localdomain
      type: Host
      file: zones.d/main/hosts/agent.localdomain.conf
      check_command: hostalive
      address: 127.0.0.1
      check_interval: 3m
    - name: generic-service
      type: Service
      file: zones.d/main/services/services.conf
      template: true
      check_interval: 300s
      retry_interval: 30s
      order: 1
    - name: ping
      type: Service
      file: zones.d/main/services/services.conf
      imports:
        - generic-service
      check_command: ping4
      assign:
        - host.address
      ignore:
        - match(no*, host.name)
    - name: group-ping
      type: ServiceGroup
      file: zones.d/main/servicegroups.conf
      display_name: "Ping Services"
      assign:
        - match(ping*, service.check_command)
    - name: group-linux
      type: HostGroup
      file: zones.d/main/hostgroups.conf
      display_name: Linux Hosts
      assign:
        - match(linux, host.vars.os)
