---

- name: Check Database Credentials
  ansible.builtin.assert:
    that:
      - icingaweb2_db['user'] is defined
      - icingaweb2_db['password'] is defined
    fail_msg: "No database credentials defined. Please set icingaweb2_db.<user|password> or a privileged user with icingaweb2_priv_db_<user|password>"
  when: icingaweb2_priv_db_password is undefined and icingaweb2_priv_db_user is undefined

- name: PostgreSQL import IDO schema
  block:
    - name: Build psql command
      ansible.builtin.set_fact:
        _tmp_pgsqlcmd: >-
          PGPASSWORD="{{ icingaweb2_priv_db_password | default(icingaweb2_db['password']) }}"
          psql
          "host={{ icingaweb2_db['host'] }}
          {% if icingaweb2_db['port'] is defined %} port={{ icingaweb2_db['port'] }} {%- endif %}
          user={{ icingaweb2_priv_db_user | default(icingaweb2_db['user']) }}
          dbname={{ icingaweb2_db['name'] }}
          {% if icingaweb2_db['ssl_mode'] is defined %} sslmode={{ icingaweb2_db['ssl_mode'] | default('require') }} {%- endif %}
          {% if icingaweb2_db['ssl_cert'] is defined %} sslcert={{ icingaweb2_db['ssl_cert']  }} {%- endif %}
          {% if icingaweb2_db['ssl_key'] is defined %} sslkey={{ icingaweb2_db['ssl_key'] }} {%- endif %}
          {% if icingaweb2_db['ssl_extra_options'] is defined %} {{ icingaweb2_db['ssl_extra_options'] }} {%- endif %}"

    - name: PostgreSQL check for IDO schema
      ansible.builtin.shell: >
        {{ _tmp_pgsqlcmd }}
        -w -c "select * from icingaweb_user"
      failed_when: false
      changed_when: false
      check_mode: false
      register: _icingaweb2_db_schema

    - name: PostgreSQL import IDO schema
      ansible.builtin.shell: >
        {{ _tmp_pgsqlcmd }}
        -w -f /usr/share/icingaweb2/schema/pgsql.schema.sql
      when: _icingaweb2_db_schema.rc != 0
  when: icingaweb2_db_import_schema | default(False)

- name: Ensure Icinga Web User
  block:
    - name: PostgreSQL check for icingaweb admin user
      ansible.builtin.shell: >
        {{ _tmp_pgsqlcmd }}
        -w -c "select name from icingaweb_user where name like '{{ icingaweb2_admin_username }}'"
      failed_when: false
      changed_when: false
      check_mode: false
      register: _icingaweb2_db_user

    - name: Ensure admin user exists
      ansible.builtin.shell: >-
        echo "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('{{ icingaweb2_admin_username }}', 1,
        '"`php -r 'echo password_hash("{{ icingaweb2_admin_password }}", PASSWORD_DEFAULT);'`"')" | {{ _tmp_pgsqlcmd }} -w
      when: '"(0 rows)" in _icingaweb2_db_user.stdout_lines'
  when:
    - icingaweb2_admin_username is defined
    - icingaweb2_admin_password is defined
