galaxy_info:
  author:
    - Matthias DÃ¶hler <matthias.doehler@netways.de>
  description: Role to install monitoring plugins as listed in the Icinga Template Library
  license: AGPL-3.0-only
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
      - 7
      - 8
  - name: Debian
    versions:
      - buster
      - bullseye
  galaxy_tags:
    - icinga
    - monitoring
  dependencies:
    - netways.icinga.repos
