---
icinga2_state: started
icinga2_enabled: true
icinga2_confd: true
icinga2_plugins:
  - plugins
  - plugins-contrib
  - windows-plugins
  - nscp
icinga2_purge_features: true
icinga2_constants: {}
icinga2_features:
  - name: checker
  - name: notification
  - name: mainlog
icinga2_remote_objects: []
