---
- name: features | icingadb | IcingaDB object
  icinga.icinga.icinga2_object:
    name: icingadb
    type: IcingaDB
    file: features-available/icingadb.conf
    args: "{{ __icinga2_dict_features.icingadb }}"
  register: result

- name: features | icingadb | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
