---

- name: features | influxdb2 | Influxdb2Writer object
  icinga.icinga.icinga2_object:
    name: influxdb2
    type: Influxdb2Writer
    file: features-available/influxdb2.conf
    args: "{{ __icinga2_dict_features.influxdb2 }}"
  register: result

- name: features | influxdb2 | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
