---

- name: features | perfdata | PerfdataWriter object
  icinga.icinga.icinga2_object:
    name: perfdata
    type: PerfdataWriter
    file: features-available/perfdata.conf
    args: "{{ __icinga2_dict_features.perfdata }}"
  register: result

- name: features | perfdata | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
